---
name: Scan for secrets

on:
  push:
    branches:
      - "**"

jobs:
  scan-for-secrets:
    name: Scan for secrets
    # ING-5175
    uses: wetransform/gha-workflows/.github/workflows/scan-for-secrets.yml@2833b293c4f20f6585f52f67e1d0b0fcb8e8f551
